### ISSUE TITLE
buildx_patch.diff missing.

### ISSUE THREAD

**Issue by makudenki** [metalefty/X11RDP-RH-Matic#40] opened 2017-03-14 06:21 UTC
This is a great utility. Thank you. One thing I would like to inform you of an error I encountered on CentOS 6.5.  SPECS/x11rdp.spec.in requires 'buildx_patch.diff' as Patch0. However, the file doesn't exist in SOURCE directory. 
```
diff --git a/SPECS/x11rdp.spec.in b/SPECS/x11rdp.spec.in
index a6dcb12..60f7be8 100644
--- a/SPECS/x11rdp.spec.in
+++ b/SPECS/x11rdp.spec.in
@@ -12,8 +12,6 @@ Release:      1%{?dist}
 URL:           http://www.xrdp.org/
 Source0:       %%GH_ACCOUNT%%-%%GH_PROJECT%%-%%GH_COMMIT%%.tar.gz

-Patch0:                buildx_patch.diff
-
 AutoReq:       no
 BuildRequires: autoconf
 BuildRequires: automake
```

**Comment by metalefty** [comment] 2017-03-14 07:04
Duplicate of #39. I'll have a look. Thanks.

**Closed by metalefty** 2017-03-14 07:04 UTC
Labels: duplicate
